In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [4]:
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
X=df.drop('total_bill',axis=1)
y=df.total_bill

In [7]:
X

      tip     sex smoker   day    time  size
0    1.01  Female     No   Sun  Dinner     2
1    1.66    Male     No   Sun  Dinner     3
2    3.50    Male     No   Sun  Dinner     3
3    3.31    Male     No   Sun  Dinner     2
4    3.61  Female     No   Sun  Dinner     4
..    ...     ...    ...   ...     ...   ...
239  5.92    Male     No   Sat  Dinner     3
240  2.00  Female    Yes   Sat  Dinner     2
241  2.00    Male    Yes   Sat  Dinner     2
242  1.75    Male     No   Sat  Dinner     2
243  3.00  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

In [8]:
from sklearn.impute import SimpleImputer #for missing vlaue
from sklearn.preprocessing import OneHotEncoder #for encoding
from sklearn.preprocessing import StandardScaler #for scaling

from sklearn.pipeline import Pipeline #A sequence of data transformers 
from sklearn.compose import ColumnTransformer #Groups all the pipeline steps for each of the clumns

In [9]:
cat_cols = ["sex", "smoker", "day","time"]
num_cols = ["tip", "size"]

In [10]:
num_pipeline = Pipeline(steps = [('imputation', SimpleImputer(strategy = "median")),
                                ('scaling', StandardScaler())])
cat_pipeline = Pipeline(steps = [('imputation', SimpleImputer(strategy = "most_frequent")),
                                ('encoding', OneHotEncoder())])

In [11]:
preprocessor = ColumnTransformer([("num_pipeline", num_pipeline, num_cols),
                  ("cat_pipeline", cat_pipeline, cat_cols)])

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [14]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

In [16]:
from sklearn.metrics import accuracy_score
def model_train_eval(X_train, y_train, X_test, y_test, models):
    evaluation = {}
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        model_score = accuracy_score(y_test, y_pred)
        evaluation[list(models.keys())[i]] = model_score
    return evaluation

In [18]:
from sklearn.ensemble import RandomForestRegressor

In [19]:
rfr = RandomForestRegressor(oob_score=True)

In [20]:
rfr

RandomForestRegressor(oob_score=True)